config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 
  get 'static_pages/help'
  root 'static_pages#home'
  get '/index' => 'static_pages#index'
  get '/user_profile/:id', to: 'static_pages#user_profile', as: 'user_profile'
  delete '/users/:id', to: 'registrations#destroy', as: 'delete_user'
  get '/signup', to: 'registration#new'
  
  #devise_for :users, controllers: {
  #imageuser: 'users/imageuser'
  #}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    before_action :admin_user, only: [:destroy]
    
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to root_path, notice: "Account has been successfully deleted."
    end
      
      
    private
    def admin_user
        unless current_user.admin?
          redirect_to index_path, notice: "Not Authorized"
          return
        end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  #before_action :logged_in_user, only: [:index]
  
  def home
  end

  def help
  end
  
  def user_profile
    @user = User.find(params[:id])
    
  end
  
  # GET /users or /users.json
  def index
    @users = User.all
    if params[:search].present?
      @users = @users.where("name LIKE ?", "%#{params[:q]}%") if params[:q].present?
    end
  end
  
  
  private
    def logged_in_user
      unless signed_in?
        flash[:alert] = "Please Log in to continue."
        redirect_to new_user_session_path
      end
    end
  

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  #def admin_user_only
  #  # Check if the current user is an admin
  #  if current_user.admin?
  #    # Find the user to cancel by its ID
  #    #user = User.find(params[:id])
  #    
  #    # Cancel the user's account
  #    user.destroy
  #    
  #    # Redirect to a success page or show a flash message
  #    redirect_to root_path, notice: "User account successfully cancelleddddd."
  #  else
  #    # If the current user is not an admin, display a message or redirect to a different page
  #    redirect_to root_path, alert: "Only admin users can cancel user accounts."
  #  end
  #end
  
 
  
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  

  
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-success-subtle">
  <div class="container-fluid">
    <%= link_to 'App Amt', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Users', index_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', '#', class:"nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              My Profile
            </a>
            <ul class="dropdown-menu">
              <li class="nav-item">
               <%= link_to 'My Profile', user_profile_path(current_user.id), class:"nav-link", class:"dropdown-item" %>
              </li>
              <li class="nav-item">
               <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link", class:"dropdown-item" %>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li class="nav-item">
               <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link", class:"dropdown-item" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Log in', new_user_session_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
   
    <%= form_tag index_path, method: :get do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search by Name", class: "search-bar " %>
        <%= submit_tag "Search", class: "search-button btn btn-outline-success"  %>
    <% end %>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>Assessment Amt</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
  </head>
  <body>
    <%= render 'layouts/header' %>
    
    <div class="container">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
    
      <%= yield %>
    </div>
    </br> </br>
    FOOTER HERE...
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/static_pages/index.html.erb
</br>
<h1> Index </h1>
<table class="table table-hover table-bordered">
    <thead class="table-success">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>User ID</th>
        <th>Admin?</th>
        
        
      </tr>
    </thead>
    
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= link_to user.email, user_profile_path(user.id) %></td>
          <td><%= user.id %></td>
          <td><%= user.admin? %></td>
      <% end %>
    </tbody>
</table>

<%= link_to "New user", '#', class:"btn btn-success" %>

app/views/static_pages/new_image.html.erb
<%= form_for @photo, html: { multipart: true } do |f| %>
    <%= f.label :image %>
    <%= f.cl_image_upload :image %>
    <%= f.submit "Upload" %>
<% end %>

app/views/static_pages/user_profile.html.erb
<h1>Profile page</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>
</br>


</br>
<%= current_user.id %><%= current_user.email %>
</br>
<%= @user.admin? %>
</br>
<%= @user.id %>
</br>

<%= @user.email %>
</br>

<%= @user.name %>
</br>



</br>
<%= button_to "Delete Account", delete_user_path(@user),method: :delete,
             data: { confirm: "Are you sure?"}, class:"btn btn-danger btn-sm" %>
             
<script>
    document.addEventListener("click", event => {
        const element = event.target.closest("[data-confirm]")

        if (element && !confirm(element.dataset.confirm)) {
            event.preventDefault()
        }
    })
</script>